### ISSUE TITLE
Would like to filter columns

### ISSUE THREAD

**Issue by jamelyassin84** [ericferreira1992/ag-table#19]
Hi  i am a  fan of your agTable i would like to filter the columns with your field directive how it works?

<ag-table #table paginate="100" [items]="admins" height="800px" min-width="650px">
        <ag-table-header>
            <ag-table-col filter="text" field="fullname" width="350px">
                Fullname
            </ag-table-col>
            <ag-table-col filter="select" field="role" width="150px">
                <span>Role</span>
            </ag-table-col>
            <ag-table-col filter="select" field="district" [options]="district" width="150px">
                <span>District</span>
            </ag-table-col>
            <ag-table-col filter="select" field="municipality" width="150px">
                <span>Muncipality</span>
            </ag-table-col>
            <ag-table-col filter="text" field="barangay" width="150px">
                <span>Barangay</span>
            </ag-table-col>
            <ag-table-col filter="date" field="created_at" no-sort="true" width="250px">
                <span> Date Created</span>
            </ag-table-col>
        </ag-table-header>

**Comment by ericferreira1992** [comment]
Hi @jamelyassin84, thanks for liking AgTable, I'm very happy for that.
Regarding your situation, I did not understand exactly what the problem is. Do you want to filter the "district" field but are not getting it?
I see that you want to use the **filter** directive of type _select_, and that you are also using the **options** directive, if the problem is with the options directive, maybe you should take a look at the documentation about it [here](https://ericferreira1992.github.io/ag-table/#/api/structure/ag-table-col). Anyway, the **options** directive accept types like `any[]` or `{ text: string, value: any }[]`, but always array.

I look forward to reply.

**Comment by jamelyassin84** [comment]
Thank you for your repply mer. eric i would like to filter a specific
column i just dont know whay should i put on the items directive ans field
directive
